### ISSUE TITLE
Errors after adding dependency

### ISSUE THREAD

**Issue by slimshader** [PixeyeHQ/actors#20]
Hi, after adding adding dependency via UPM, bunch of errors pop up:

Library/PackageCache/com.pixeye.ecs@b0136155b5/Editor/Drawers/DrawerScene.cs(22,31): error CS0246: The type or namespace name 'SceneReference' could not be found (are you missing a using directive or an assembly reference?)

Library/PackageCache/com.pixeye.ecs@b0136155b5/Editor/Drawers/DrawerInfoBox.cs(10,34): error CS0246: The type or namespace name 'InfoBoxAttribute' could not be found (are you missing a using directive or an assembly reference?)

Library/PackageCache/com.pixeye.ecs@b0136155b5/Editor/Drawers/DrawerScene.cs(22,31): error CS0246: The type or namespace name 'SceneReference' could not be found (are you missing a using directive or an assembly reference?)

Library/PackageCache/com.pixeye.ecs@b0136155b5/Editor/Drawers/DrawerTags.cs(14,31): error CS0246: The type or namespace name 'TagFilterAttribute' could not be found (are you missing a using directive or an assembly reference?)

Library/PackageCache/com.pixeye.ecs@b0136155b5/Editor/Drawers/DrawerTags.cs(22,10): error CS0246: The type or namespace name 'FastString' could not be found (are you missing a using directive or an assembly reference?)

Library/PackageCache/com.pixeye.ecs@b0136155b5/Editor/SceneProcessors/PostHandlePools.cs(66,70): error CS0246: The type or namespace name 'Starter' could not be found (are you missing a using directive or an assembly reference?)

Library/PackageCache/com.pixeye.ecs@b0136155b5/Editor/Inspector/InspectorOverride.cs(279,11): error CS0246: The type or namespace name 'FoldoutGroupAttribute' could not be found (are you missing a using directive or an assembly reference?)

Library/PackageCache/com.pixeye.ecs@b0136155b5/Editor/Inspector/InspectorReordarable.cs(439,41): error CS0246: The type or namespace name 'ReorderableAttribute' could not be found (are you missing a using directive or an assembly reference?)

**Comment by PixeyeHQ** [comment]
Hey @slimshader , what kind of dependency?

**Comment by slimshader** [comment]
Actors dependency via
```"com.pixeye.ecs": "https://github.com/dimmpixeye/actors.git"```
to the packages of course ;)

**Comment by PixeyeHQ** [comment]
@slimshader ye, I've messed with metafiles, sorry.
Try now to update. Also make sure your Pixeye.Source file got Pixeye.Actors lib

![a66c5c4e6aaab5b1b0769263c29b8791](https://user-images.githubusercontent.com/19838200/79415259-2d0b3380-7fad-11ea-9437-a6e7a9785305.png)

**Comment by PixeyeHQ** [comment]
closing as there was no response for a long time.
