### ISSUE TITLE
Package version of release 2020.04.16 is not updated

### ISSUE THREAD

**Issue by favoyang** [PixeyeHQ/actors#21]
[Package.json version](https://github.com/PixeyeHQ/actors/blob/2020.04.16/package.json) of release 2020.04.16 is not updated.

**Comment by favoyang** [comment]
Considering forget to update the version string of package.json is a common mistake. It happens quite a few times. For example, 2020.04.16, 2020.03.10a, and 2020.02.29. I would suggest
- [An automatic approach](https://medium.com/openupm/how-to-maintain-upm-package-part-2-f352fbf5f87c).
- But that breaks the style of using the date string as version number, you may need find some tools like [release-it](https://www.npmjs.com/package/release-it) but can specify a version number manually.

**Comment by PixeyeHQ** [comment]
thanks for pointing that :) I will fix that asap.
